Added implementation to use user provided access token for existing connections and generate new access token for new connections using refresh token
singer-io/tap-linkedin-ads pull request #43
Opened 2022-06-20 10:29 UTC by RushT007

# Description of change
- Added implementation to use user provided access token for existing connections and generate new access token for new connections using refresh token
- Added tap-tester to test existing connection scenario i.e. no refresh token provided
- Added the unittest to test access token creation
- Updated existing unittests

# Manual QA steps
[] Verify that sync works when refresh token in not provided in config properties
[] Verify the discovery fails when token is expired or invalid
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-06-21 04:08 UTC, KrisPersonal approved these changes

2022-06-21 12:10 UTC, cosimon requested changes

2022-06-21 12:10 UTC, cosimon commented on tap_linkedin_ads/__init__.py
> +from os import access
Do we need this import?

2022-06-21 12:10 UTC, cosimon commented on tests/unittests/test_timeout.py
> +            client_secret=config['client_secret'],
Please align these correctly with the `client_id`

2022-06-22 04:31 UTC, RushT007 commented
@cosimon I have fixed all the issues and also successfully run the alpha for internal stitch client.

2022-06-22 13:28 UTC, cosimon requested changes

2022-06-22 13:28 UTC, cosimon commented on tap_linkedin_ads/client.py
> +        Note: Linkedin-ads access token expires in 90 days, where as refresh token expires in 365 days.
Access tokens expire in 60 days, not 90. Please update this comment.

2022-06-22 13:28 UTC, cosimon commented on tests/unittests/test_timeout.py
> +            request_timeout=config.get('request_timeout'))
Please align them like this:
```suggestion
        cl = client.LinkedinClient(client_id=config['client_id'],
                                   client_secret=config['client_secret'],
                                   refresh_token=config['refresh_token'],
                                   access_token=config['access_token'],
                                   user_agent=config['user_agent'],
                                   request_timeout=config.get('request_timeout'))
```

2022-06-22 14:06 UTC, RushT007 commented on tests/unittests/test_timeout.py
> +            request_timeout=config.get('request_timeout'))
Made the changes, please re-review.

2022-06-23 14:04 UTC, cosimon approved these changes

2022-06-23 15:15 UTC, merged